name: Deploy Env
description: Deploys the infrastrcuture and apps to an environment
inputs:
  stage:
    description: Environment to deploy on
    required: true
    default: dev
  secrets:
    description: Secrets
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ fromJSON(inputs.secrets).AWS_ACCESS_KEY_ID }}
        aws-region: ${{ fromJSON(inputs.secrets).AWS_REGION }}
        aws-secret-access-key: ${{ fromJSON(inputs.secrets).AWS_SECRET_ACCESS_KEY }}
    - name: Install pulumi
      uses: pulumi/setup-pulumi@v2
    - name: Login to Pulumi backend
      working-directory: stream/infra
      shell: bash
      run: pulumi login s3://nftcom-pulumi-state
    - name: Install Shared Deps
      working-directory: NFT-backend/infra
      shell: bash
      run:  npm ci
    - name: Install Infra Deps
      working-directory: stream/infra
      shell: bash
      run:  npm install
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        working-directory: stream
        filters: |
          stream:
            - 'infra/**'
    - name: Deploy Strean Shared Infra
      working-directory: stream/infra
      shell: bash
      env:
        STAGE: ${{ inputs.stage }}
        PULUMI_CONFIG_PASSPHRASE: ""
        AWS_ACCOUNT_ID: ${{ fromJSON(inputs.secrets).AWS_ACCOUNT_ID }}
        DB_PASSWORD: ${{ fromJSON(inputs.secrets).DB_PASSWORD }}
      run: npm run deploy:shared
    - name: Deploy Stream Infra
      if: ${{ inputs.stage == 'prod' || steps.filter.outputs.stream == 'true' }}
      shell: bash
      working-directory: stream/infra
      env:
        STAGE: ${{ inputs.stage }}
        PULUMI_CONFIG_PASSPHRASE: ""
        AWS_ACCOUNT_ID: ${{ fromJSON(inputs.secrets).AWS_ACCOUNT_ID }}
        ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
      run: npm run deploy:stream
