name: Stream github actions
on:
  push:
    paths:
      - 'infra/stream/**.ts'
      - 'infra/stream/**.yaml'
      - 'packages/stream/**.ts'
jobs:
  deploy-dev:
    if: ${{ startsWith(github.ref_name, 'feat') || startsWith(github.ref_name, 'fix') || github.ref_name == 'main' }}
    runs-on: [self-hosted]
    environment: nftcom_stream_dev
    steps:
      - uses: actions/checkout@v3
      - uses: ./stream/.github/actions/deploy-env
        name: Deploy env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: dev
  deploy-staging:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'staging') }}
    runs-on: [self-hosted]
    environment: nftcom_stream_staging
    steps:
      - uses: actions/checkout@v3
      - uses: ./stream/.github/actions/deploy-env
        name: Deploy Staging Env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: staging
  deploy-prod:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'rel') }}
    runs-on: ubuntu-latest
    environment: nftcom_stream_prod
    steps:
      - uses: actions/checkout@v3
      - uses: ./stream/.github/actions/deploy-env
        name: Deploy Prod Env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: prod