name: NFT.com github actions
on: [push]
jobs:
  deploy-dev:
    if: ${{ startsWith(github.ref_name, 'feat') || startsWith(github.ref_name, 'fix') || github.ref_name == 'main' }}
    runs-on: [self-hosted]
    environment: nftcom_stream_dev
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          token: ${{secrets.CROSSREPO_PAT}}
          repository: NFT-com/NFT-backend
          ref: main
          path: NFT-backend
      - uses: actions/checkout@v3
        with:
          path: stream
      - uses: ./stream/.github/actions/deploy-env
        name: Deploy env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: dev
  deploy-staging:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'staging') }}
    runs-on: [self-hosted]
    environment: nftcom_stream_staging
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          token: ${{secrets.CROSSREPO_PAT}}
          repository: NFT-com/NFT-backend
          ref: main
          path: NFT-backend
      - uses: actions/checkout@v3
        with:
          path: stream
      - uses: ./stream/.github/actions/deploy-env
        name: Deploy Staging Env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: staging
  deploy-prod:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'rel') }}
    runs-on: ubuntu-latest
    environment: nftcom_stream_prod
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          token: ${{secrets.CROSSREPO_PAT}}
          repository: NFT-com/NFT-backend
          ref: main
          path: NFT-backend
      - uses: actions/checkout@v3
        with:
          path: stream
      - uses: ./stream/.github/actions/deploy-env
        name: Deploy Prod Env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: prod